version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: buscacep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    networks:
      - buscacep-network

  backend:
    image: devritter/buscacep-prod
    container_name: buscacep
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    networks:
      - buscacep-network

  frontend:
    build: ./frontend
    container_name: buscacep-front
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - buscacep-network

networks:
  buscacep-network:
    driver: bridge
